version: '3'
services:
  hana:
    image: store/saplabs/hanaexpress:2.00.040.00.20190729.1
    container_name: hana
    hostname: hana
    sysctls:
      - net.ipv4.ip_local_port_range=40000 60999
    entrypoint:
      - sh
      - -c
      - echo "{\"master_password\":\"HXEHana1\"}" > /tmp/hana_password.json; cat /tmp/hana_password.json;/run_hana --agree-to-sap-license --passwords-url file:///tmp/hana_password.json
    ports:
      - 39013:39013 
      - 39017:39017
      - 39041-39045:39041-39045
    ulimits:
      nofile: 1048576

  postgres:
    build:
      dockerfile: Dockerfile-postgis
      context: ../../../tests/testdata
    environment:
      - ALLOW_IP_RANGE="172.18.0.0/16"
# The following files are added in Dockerfile-postgis
      - SSL_CERT_FILE=/etc/ssl/certs/postgres_cert.crt
      - SSL_KEY_FILE=/etc/ssl/private/postgres_key.key
      - SSL_CA_FILE=/etc/ssl/certs/issuer_ca_cert.pem

  oracle:
    image: oslandia/oracle-for-qgis-tests-configured:18.4.0-xe
    environment:
      - ORACLE_SID=XE
      - ORACLE_PWD=adminpass
      - ORACLE_PDB=ORCLPDBTEST
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - 1521:1521

# Proving very fragile!
#  mssql:
#    image: microsoft/mssql-server-linux:2017-latest
#    environment:
#      ACCEPT_EULA: Y
#      SA_PASSWORD: <YourStrong!Passw0rd>

  qgis-deps:
    tty: true
    image: qgis_image
    volumes:
      - ${TRAVIS_BUILD_DIR}:/root/QGIS
    links:
      - hana
      - postgres
      - oracle
    #  - mssql
    env_file:
      - docker-variables.env
